/********************************************************************
* dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledict();
extern void G__cpp_setup_inheritancedict();
extern void G__cpp_setup_typetabledict();
extern void G__cpp_setup_memvardict();
extern void G__cpp_setup_globaldict();
extern void G__cpp_setup_memfuncdict();
extern void G__cpp_setup_funcdict();
extern void G__set_cpp_environmentdict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/opt/DetectorSimulations/detectorSimulations/dataRootClass/TSpiceData.cpp"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dictLN_TClass;
extern G__linked_taginfo G__dictLN_TBuffer;
extern G__linked_taginfo G__dictLN_TMemberInspector;
extern G__linked_taginfo G__dictLN_TObject;
extern G__linked_taginfo G__dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__dictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__dictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__dictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__dictLN_TVector3;
extern G__linked_taginfo G__dictLN_TSpiceData;
extern G__linked_taginfo G__dictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictLN_vectorlETVector3cOallocatorlETVector3gRsPgR;
extern G__linked_taginfo G__dictLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
