/********************************************************************
* TGriffinDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TGriffinDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGriffinDataDict();
extern void G__cpp_setup_inheritanceTGriffinDataDict();
extern void G__cpp_setup_typetableTGriffinDataDict();
extern void G__cpp_setup_memvarTGriffinDataDict();
extern void G__cpp_setup_globalTGriffinDataDict();
extern void G__cpp_setup_memfuncTGriffinDataDict();
extern void G__cpp_setup_funcTGriffinDataDict();
extern void G__set_cpp_environmentTGriffinDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TGriffinData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGriffinDataDictLN_TClass;
extern G__linked_taginfo G__TGriffinDataDictLN_TBuffer;
extern G__linked_taginfo G__TGriffinDataDictLN_TMemberInspector;
extern G__linked_taginfo G__TGriffinDataDictLN_TObject;
extern G__linked_taginfo G__TGriffinDataDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TGriffinDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGriffinDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGriffinDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGriffinDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGriffinDataDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TGriffinDataDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TGriffinDataDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TGriffinDataDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TGriffinDataDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TGriffinDataDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TGriffinDataDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TGriffinDataDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TGriffinDataDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TGriffinDataDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TGriffinDataDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TGriffinDataDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TGriffinDataDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TGriffinDataDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TGriffinDataDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TGriffinDataDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TGriffinDataDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TGriffinDataDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TGriffinDataDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TGriffinDataDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TGriffinDataDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TGriffinDataDictLN_TVector3;
extern G__linked_taginfo G__TGriffinDataDictLN_TGriffinData;
extern G__linked_taginfo G__TGriffinDataDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TGriffinDataDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGriffinDataDictLN_vectorlETVector3cOallocatorlETVector3gRsPgR;
extern G__linked_taginfo G__TGriffinDataDictLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
