/********************************************************************
* TS3DataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TS3DataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTS3DataDict();
extern void G__cpp_setup_inheritanceTS3DataDict();
extern void G__cpp_setup_typetableTS3DataDict();
extern void G__cpp_setup_memvarTS3DataDict();
extern void G__cpp_setup_globalTS3DataDict();
extern void G__cpp_setup_memfuncTS3DataDict();
extern void G__cpp_setup_funcTS3DataDict();
extern void G__set_cpp_environmentTS3DataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TS3Data.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TS3DataDictLN_TClass;
extern G__linked_taginfo G__TS3DataDictLN_TBuffer;
extern G__linked_taginfo G__TS3DataDictLN_TMemberInspector;
extern G__linked_taginfo G__TS3DataDictLN_TObject;
extern G__linked_taginfo G__TS3DataDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TS3DataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TS3DataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TS3DataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TS3DataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TS3DataDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TS3DataDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TS3DataDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TS3DataDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TS3DataDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TS3DataDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TS3DataDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TS3DataDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TS3DataDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TS3DataDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TS3DataDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TS3DataDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TS3DataDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TS3DataDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TS3DataDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TS3DataDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TS3DataDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TS3DataDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TS3DataDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TS3DataDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TS3DataDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TS3DataDictLN_TVector3;
extern G__linked_taginfo G__TS3DataDictLN_TS3Data;
extern G__linked_taginfo G__TS3DataDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TS3DataDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TS3DataDictLN_vectorlETVector3cOallocatorlETVector3gRsPgR;
extern G__linked_taginfo G__TS3DataDictLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
