/********************************************************************
* TSpiceDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TSpiceDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTSpiceDataDict();
extern void G__cpp_setup_inheritanceTSpiceDataDict();
extern void G__cpp_setup_typetableTSpiceDataDict();
extern void G__cpp_setup_memvarTSpiceDataDict();
extern void G__cpp_setup_globalTSpiceDataDict();
extern void G__cpp_setup_memfuncTSpiceDataDict();
extern void G__cpp_setup_funcTSpiceDataDict();
extern void G__set_cpp_environmentTSpiceDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TSpiceData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TSpiceDataDictLN_TClass;
extern G__linked_taginfo G__TSpiceDataDictLN_TBuffer;
extern G__linked_taginfo G__TSpiceDataDictLN_TMemberInspector;
extern G__linked_taginfo G__TSpiceDataDictLN_TObject;
extern G__linked_taginfo G__TSpiceDataDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TSpiceDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TSpiceDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSpiceDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TSpiceDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSpiceDataDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TSpiceDataDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TSpiceDataDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TSpiceDataDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TSpiceDataDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TSpiceDataDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TSpiceDataDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TSpiceDataDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TSpiceDataDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TSpiceDataDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TSpiceDataDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TSpiceDataDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TSpiceDataDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TSpiceDataDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TSpiceDataDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TSpiceDataDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TSpiceDataDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TSpiceDataDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TSpiceDataDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TSpiceDataDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TSpiceDataDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TSpiceDataDictLN_TVector3;
extern G__linked_taginfo G__TSpiceDataDictLN_TSpiceData;
extern G__linked_taginfo G__TSpiceDataDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TSpiceDataDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSpiceDataDictLN_vectorlETVector3cOallocatorlETVector3gRsPgR;
extern G__linked_taginfo G__TSpiceDataDictLN_reverse_iteratorlEvectorlETVector3cOallocatorlETVector3gRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
